version: '3'

services:
  rails:
    build: .
    image: fabianaramos/ubuntu-rails-ssh:16.04
    volumes:
      - .:/projects
    ports:
      - "3000"
      - "22"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"

